name: CI/CD Pipeline

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
    
    - name: Run tests
      run: |
        pip install pytest
        pytest tests/
    
    - name: Train model
      run: python src/train_m1.py
    
    - name: Archive model
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: models/iris_model.joblib

    - name: Build Docker image
      run: |
        docker build -t mlops-assignment .
    
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push to Docker Hub
      run: |
        docker tag mlops-assignment ${{ secrets.DOCKER_USERNAME }}/mlops-assignment
        docker push ${{ secrets.DOCKER_USERNAME }}/mlops-assignment